name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - run: mvn clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: mvn test

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - run: echo "Deploy realizado com sucesso"
