name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Executar testes?'
        required: true
        default: true
        type: boolean
      run_lint:
        description: 'Executar lint?'
        required: true
        default: true
        type: boolean

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build com Maven
        run: mvn clean install


  package:
    runs-on: ubuntu-latest
    needs: [build, lint-and-test]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gera o .jar
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Simula Deploy
        run: echo "Deploy realizado com sucesso"

  codeql-analysis:
    name: Análise de Segurança com CodeQL
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Analisar com CodeQL
        uses: github/codeql-action/analyze@v2

  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    with:
      run_tests: ${{ inputs.run_tests }}
      run_lint: ${{ inputs.run_lint }}



