name: Lint and Test

on:
  workflow_call:
    inputs:
      run_tests:
        required: true
        type: boolean
      run_lint:
        required: true
        type: boolean

jobs:
  lint:
    if: ${{ inputs.run_lint }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verifica estilo com Checkstyle
        run: mvn checkstyle:check

  test:
    if: ${{ inputs.run_tests }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executa os testes
        run: mvn test
