name: Variáveis e Secrets

on:
  workflow_dispatch:

jobs:
  mostrar-variaveis:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir variáveis públicas
        run: |
          echo "APP_MODE: ${{ vars.APP_MODE }}"
          echo "SUPPORT_EMAIL: ${{ vars.SUPPORT_EMAIL }}"

      - name: Simular uso de segredo sensível
        run: |
          echo "Autenticando com PROD_TOKEN (simulado)"
          echo "Início do token: ${SECRET_INICIAL}"
        env:
          SECRET_INICIAL: ${{ secrets.PROD_TOKEN }}
